export const REPO_CHANGED = 'REPO_CHANGED';

export const LOAD_REPO = 'LOAD_REPO';
export const REPO_REQUEST = 'REPO_REQUEST';
export const REPO_SUCCESS = 'REPO_SUCCESS';
export const REPO_FAILURE = 'REPO_FAILURE';

export const LOAD_STARGAZERS = 'LOAD_STARGAZERS';
export const LOAD_MORE_STARGAZERS = 'LOAD_MORE_STARGAZERS';
export const STARGAZERS_REQUEST = 'STARGAZERS_REQUEST';
export const STARGAZERS_SUCCESS = 'STARGAZERS_SUCCESS';
export const STARGAZERS_FAILURE = 'STARGAZERS_FAILURE';
