export const USER_CHANGED = 'USER_CHANGED';

export const LOAD_USER = 'LOAD_USER';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const LOAD_STARRED = 'LOAD_STARRED';
export const LOAD_MORE_STARRED = 'LOAD_MORE_STARRED';
export const STARRED_REQUEST = 'STARRED_REQUEST';
export const STARRED_SUCCESS = 'STARRED_SUCCESS';
export const STARRED_FAILURE = 'STARRED_FAILURE';
